
#include "responsive_window.h"
#include "responsive_layout.h"
#include "screenshot.h"
#include <iostream>
#include <QApplication>


ResponsiveWindow::ResponsiveWindow() {

    setWindowTitle("2811: Coursework 1");
    setMinimumSize(320, 320);

    createWidgets();
}

void ResponsiveWindow::createWidgets() {

    ResponsiveLayout * rl = new ResponsiveLayout();
    rl->addWidget(new ResponsiveLabel(kNavTabs));
    rl->addWidget(new ResponsiveLabel(kSearchButton));
	rl->addWidget(new ResponsiveLabel(kBackButton));
    rl->addWidget(new ResponsiveLabel(kSearchOptions));
	rl->addWidget(new ResponsiveLabel(kSearchText));
	rl->addWidget(new ResponsiveLabel(kAdvert));
	rl->addWidget(new ResponsiveLabel(kShoppingBasket));
	rl->addWidget(new ResponsiveLabel(kHomeLink));
	rl->addWidget(new ResponsiveLabel(kSearchResult));
	rl->addWidget(new ResponsiveLabel(kAdvert1));
	rl->addWidget(new ResponsiveLabel(kAdvert2));
	rl->addWidget(new ResponsiveLabel(kAdvert3));
	rl->addWidget(new ResponsiveLabel(kAdvert4));
	rl->addWidget(new ResponsiveLabel(kSearchBackward));
	rl->addWidget(new ResponsiveLabel(kSearchForward));
	rl->addWidget(new ResponsiveLabel(kInterest));
	rl->addWidget(new ResponsiveLabel(kFooter));

    setLayout(rl);
}

// please DO NOT edit this file beyond this line
int main(int argc, char *argv[]) {

    // create the Qt Application
    QApplication app(argc, argv);

    // create a window. See respsonsive_window.cpp!
    if (argc-1)  {
        // grading-mode - run the screenshot subclass
        Screenshot screenshot;
        screenshot.show();
        // wait for the app to terminate
        return app.exec();
    } else {
        // interactive mode - run the regular superclass
        ResponsiveWindow window;
        window.show();
        // wait for the app to terminate
        return app.exec();
    }

}

